context:
  name: micro-cdr
  version: "2.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  #git: https://github.com/eProsima/Micro-CDR.git
  #tag: v${{ version }}
  url: https://github.com/eProsima/Micro-CDR/archive/refs/tags/v${{ version }}.tar.gz
  sha256: bcc16517acc55a58fad6d39cfa42ba3658e2c7d0f408af5b1a27b634072d64b6

build:
  number: 0
  script:
    - |
      cmake -S $SRC_DIR -B build -G "Ninja" \
        -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DUCDR_SUPERBUILD=OFF \
        -DBUILD_SHARED_LIBS=ON
    - cmake --build build --target install

requirements:
  host:
    - cmake
    - compilers
    - ninja
  run: []

tests:
  - script: []

about:
  homepage: https://github.com/eProsima/Micro-CDR
  summary: Micro CDR serialization library
  description: |
    eProsima Micro CDR is a C library implementing the CDR standard
    serialization methods. This library is focused on embedded and
    resource-limited systems.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://github.com/eProsima/Micro-CDR 
  repository: https://github.com/eProsima/Micro-CDR
