context:
  name: ardupilot-dds-tests
  version: "4.8.0"
  distro: jazzy

package:
  name: ros-${{ distro }}-${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ArduPilot/ardupilot.git
  rev: 8530bf14d1768057ed88cf3a9c1a5db42e32d06c

build:
  number: 1
  script:
    - $PYTHON -m pip install ${SRC_DIR}/Tools/ros2/ardupilot_dds_tests --no-deps -vv

requirements:
  build:
    - python >=3.12,<3.13
  host:
    - python >=3.12,<3.13
    - pip
    - ros-${{ distro }}-ament-cmake
    - ros-${{ distro }}-ament-cmake-pytest
    - ros-${{ distro }}-ament-lint-auto
    - ros-${{ distro }}-ament-cmake-python
  run:
    - python >=3.12,<3.13
    - ros-${{ distro }}-ament-index-python
    - ros-${{ distro }}-ardupilot-msgs >=4.8.0
    - ros-${{ distro }}-ardupilot-sitl >=4.8.0
    - ros-${{ distro }}-launch
    - ros-${{ distro }}-launch-pytest
    - ros-${{ distro }}-launch-ros
    - ros-${{ distro }}-micro-ros-agent >=5.0.2,<6
    - ros-${{ distro }}-micro-ros-msgs >=5.0.2,<6
    - ros-${{ distro }}-rclpy
    - socat

tests:
  - script: []

about:
  homepage: https://github.com/ArduPilot/ardupilot
  summary: This is a colcon package for running ArduPilot SITL using the ROS 2
  description: |
    ROS 2 packages and configuration files for running ROS 2 processes and
    nodes that communicate with the ArduPilot DDS client library using the
    microROS agent.
  license: GPL-3.0-only
