context:
  name: ardupilot-gz-bringup
  version: "0.1.0"
  distro: kilted
  gz_version: ionic

package:
  name: ros-${{ distro }}-${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ArduPilot/ardupilot_gz.git
  rev: 8df4dc1726e37504e6fc8b952d02e554cfa3176f

build:
  number: 0
  script:
    env:
      GZ_VERSION: ${{ gz_version }}
    content:
      - |
        cmake -S $SRC_DIR/ardupilot_gz_bringup -B build -G "Ninja" \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DBUILD_SHARED_LIBS=ON \
          -DPython3_EXECUTABLE=$PREFIX/bin/python \
          -DCMAKE_INSTALL_LIBDIR=lib \
      - cmake --build build --target install

requirements:
  build:
    - python >=3.12,<3.13
  host:
    - compilers
    - cmake
    - ninja
    - python >=3.12,<3.13
    - ros-${{ distro }}-ament-cmake
    - ros-${{ distro }}-ament-cmake-pytest
    - ros-${{ distro }}-ament-cmake-python
    - ros-${{ distro }}-ament-index-python
    - ros-${{ distro }}-ament-lint-auto
    - ros-${{ distro }}-ament-lint-common
    - ros-${{ distro }}-ardupilot-gazebo
    - ros-${{ distro }}-ardupilot-gz-description
    - ros-${{ distro }}-ardupilot-gz-gazebo
    - ros-${{ distro }}-ardupilot-sitl
    - ros-${{ distro }}-launch
    - ros-${{ distro }}-launch-ros
    - ros-${{ distro }}-ros-gz-sim
    - ros-${{ distro }}-gps-msgs

  run:
    - python >=3.12,<3.13
    - ros-${{ distro }}-ardupilot-sitl-models
    - ros-${{ distro }}-gz-sim-vendor = 0.2
    - ros-${{ distro }}-ros-gz-bridge
    - ros-${{ distro }}-robot-state-publisher
    - ros-${{ distro }}-sdformat-urdf
    - ros-${{ distro }}-topic-tools

tests:
  - script: []


about:
  homepage: https://github.com/ArduPilot/ardupilot_gz
  summary: Tools for ArduPilot ROS2 integration and testing on ROS 2
  description: |
    This project contains ROS 2 packages for simulating models controlled
    by ArduPilot SITL with DDS support in Gazebo.
  license: GPL-3.0-only
