context:
  name: ardupilot-msgs
  version: "4.7.0"
  distro: kilted

package:
  name: ros-${{ distro }}-${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ArduPilot/ardupilot.git
  rev: 571e8c7bd3793fce1bc5184a2f6586feb8a616e5

build:
  number: 0
  script:
    - |
      cmake -S ${SRC_DIR}/Tools/ros2/ardupilot_msgs -B build -G "Ninja" \
        -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DPython3_EXECUTABLE=$PREFIX/bin/python \
        -DCMAKE_INSTALL_LIBDIR=lib \
    - cmake --build build --target install

requirements:
  build:
    - python >=3.12,<3.13
  host:
    - compilers
    - cmake
    - micro-xrce-dds-gen >=4.7.2,<5
    - ninja
    - python >=3.12,<3.13
    - ros-kilted-ament-cmake
    - ros-kilted-ament-cmake-pytest
    - ros-kilted-ament-lint-auto
    - ros-kilted-geometry-msgs
    - ros-kilted-rosidl-default-generators
    - ros-kilted-rosidl-default-runtime
    - ros-kilted-std-msgs
  run:
    - python >=3.12,<3.13

tests:
  - script: []

about:
  homepage: https://github.com/ArduPilot/ardupilot
  summary: Custom ROS 2 messages and services for ArduPilot
  description: |
    Custom ROS 2 messages and services for ArduPilot.
  license: GPL-3.0-only
