context:
  name: micro-ros-msgs
  version: "5.0.2"
  distro: jazzy

package:
  name: ros-${{ distro }}-${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/micro-ROS/micro_ros_msgs.git
  tag: ${{ version }}
  expected_commit: 4594d9db17db735b1e655141fb4afb4cdcfc5789

build:
  number: 0
  script:
    - |
      cmake -S ${SRC_DIR} -B build -G "Ninja" \
        -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DPython3_EXECUTABLE=$PREFIX/bin/python \
        -DCMAKE_INSTALL_LIBDIR=lib \
    - cmake --build build --target install

requirements:
  build:
    - python >=3.12,<3.13
  host:
    - compilers
    - cmake
    - ninja
    - python >=3.12,<3.13
    - ros-${{ distro }}-ament-cmake
    - ros-${{ distro }}-ament-lint-auto
    - ros-${{ distro }}-rosidl-default-generators
    - ros-${{ distro }}-rosidl-default-runtime
  run:
    - python >=3.12,<3.13
    - ros-${{ distro }}-rosidl-default-runtime

tests:
  - script: []


about:
  homepage: https://github.com/micro-ROS/micro_ros_msgs
  summary: Collection of ROS 2 message definitions used in micro-ROS
  description: |
    Collection of ROS 2 message definitions used throughout the implementation
    of micro-ROS, both in the server (micro-ROS Agent) and
    client (micro-ROS RMW) endpoints.
  license: Apache-2.0
  license_file: LICENSE
